### ISSUE TITLE
Error status and error message undefined

### ISSUE THREAD

**Issue by duffyg** [pwlin/cordova-plugin-file-opener2#113]
After writing a PDF file to `cordova.file.externalDataDirectory` I try to open it using this code:

    console.log('Successful file write: ' + path);
    cordova.plugins.fileOpener2.open(path, 'application/pdf', { 
        error : function(e) {console.log('Error status: ' + e.status + ' - Error message: ' + e.message);},
        success : function () {console.log('File opened successfully');}
    });

The logs show:

    Successful file write: file:///storage/emulated/0/Android/data/com.example.app/files/p-2017-03.pdf
    Error status: undefined - Error message: undefined

The file can be manually opened OK through a file manager. This was working fine until a recent Samsung upgrade.

**Comment by pwlin** [comment]
1. What is the final value of `path`?
2. Try to open your pdf file with [InAppBrowser plugin](https://github.com/apache/cordova-plugin-inappbrowser). Does that work?

**Comment by duffyg** [comment]
It's someone else's phone, unfortunately, who submitted the bug report. It's working fine on my own test  Android, of course. Could you explain your line of reasoning, please? If InAppBrowser works, what does it prove?

**Comment by pwlin** [comment]
It's an official Cordova plugin for opening basic stuff like pdf files or external html pages. It has a bigger community behind it which might be able to help you better. If you can't get it to work either, it might be an indication that your problem lies somewhere else, probably a wrongly formatted `path`. There were some major changes since Android 6 for construction a file path. Use a different protocol (`cdv://` or `content://`) to construct your path. Experiment with other `cordova.file.*` locations (test `toUrl()`).

Find out on which Android versions it works and one which ones it doesn't.

**Comment by duffyg** [comment]
I upgraded from 2.0.3 to 2.0.15 of File Opener2 and it's working fine now.

**Comment by pwlin** [comment]
Glad to hear that. Yeah, it always helps to upgrade to the latest version before thinking you have a bug.
