### ISSUE TITLE
Default Application Issue when opening Different File Extensions

### ISSUE THREAD

**Issue by OmarHallab** [pwlin/cordova-plugin-file-opener2#115]
Hi,

I am having an issue when selecting the default application to open my files.

Basically once Files are downloaded successfully the "Open with" Dialog opens up,  if I select ( lets say Excel ) as my default application , it will always open in Excel regardless of the File extension ( PDF, Word, PPT, etc...)

Any ideas on how I can resolve this Issue? My application needs to support multiple file extensions & they should open with their respective applications by default. 

Thanks & appreciate your work

**Comment by pwlin** [comment]
on which file extension this happens exactly?

**Comment by OmarHallab** [comment]
Once the Default Application has been selected, all file extensions will try to open in that Default Application.

Images, PDFs, Word , PowerPoint etc... will always try to open with "Excel" for example. (which of course fails because Excel doesn't support the File types )

**Comment by OmarHallab** [comment]
Latest Android Version 7 Nougat.

**Comment by pwlin** [comment]
I think you might have a problem with your device. 

Usually when you open a file with an app, Android asks you if you want to use it as default application. If you choose not to, it will continue to prompt you every time.

It seems in your case that functionality is not working properly.

**Comment by OmarHallab** [comment]
I don't think it is device related , because I have tried my application on several android devices all of which had the same Issue.

In my case, I choose the first time the default application as Excel for xsl documents to automatically open ( which works fine ). 

But whenever I open a different type of document (.docx .pdf, .jpg) , it doesn't prompt & tries to open the document in Excel. 

While opening the file using File-Opener plug in , I am checking for document type. Can you please check on this behavior from your side ? 

My aim is to open all the document files in their respective applications ( set by default ) 

Best Regards,

**Comment by pwlin** [comment]
>While opening the file using File-Opener plug in , I am checking for document type.

Why would you do something like that?

I really wish I could help you, but I still can not understand how opening an xsl file can have any effect whatsoever on opening a docx file? 

>My aim is to open all the document files in their respective applications ( set by default )

But that has nothing to do with this plugin! That is something managed by the device itself. This plugin does not do anything special other than asking Android to open a file. There is no secret or mystery going on here and you don't need to hack your way into some strange way of doing stuff.

You should get a better understanding of what exactly you are trying to achieve. Because frankly, I am not sure what are you expecting this plugin to do.
