### ISSUE TITLE
iOS issue- App is closed on click of save image option from file opener.

### ISSUE THREAD

**Issue by bandhavya** [pwlin/cordova-plugin-file-opener2#118]
File opener for opening a image in ios shows save Image option along with other options like mail, add to notes etc. On click of save image option, app is getting closed.

**Comment by pwlin** [comment]
Can you debug your app to see what kind of error you are getting?

**Comment by amanvishnani** [comment]
This issue is related to "NSPhotoLibraryUsageDescription" not provided while plugin installation. The official [camera plugin](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-camera/index.html) has solved this problem, check out its iOS Quirks section.

This [Plugin](https://www.npmjs.com/package/cordova-plugin-ios-camera-permissions) also promises to solve the issue have a look at it.
