### ISSUE TITLE
Files without file extension on iOS

### ISSUE THREAD

**Issue by deltragon** [pwlin/cordova-plugin-file-opener2#150]
In our project, we use local files that do not have file extensions.
While this does work on android, it fails on iOS since iOS ignores the mimetype that is passed in and tries to sniff the file extension instead.
It would be useful to have an interface that forces the use of the mimetype over the file extension for iOS.

**Comment by deltragon** [comment]
Will submit a pull request.

**Comment by deltragon** [comment]
This could also be resolved using something like https://github.com/kimar/MagicKit-iOS to detect the mimetype from the file itself (magic numbers), which would make the behaviour consistent across all platforms once android's native mimetype detection is used as well.

**Comment by pwlin** [comment]
If I understand this correctly: because you have files without any file extension, you want to force MIME types in iOS? Is there any other reason for forcing a mime type in iOS? As iOS detects 99.99999999% of the files when they do have a file extension.

**Comment by deltragon** [comment]
"when they do have a file extension": exactly my problem, my files do not have file extensions, so iOS can't detect it currently, which is why I'd like to provide mime types.

**Comment by pwlin** [comment]
OK I understand what you mean. But I think adding an extra parameter to "force" the mime type is not the optimal way to go. 

Isn't it better to assume: if you provide a mime type, it should be forced on all platforms. If you want automatically detection of the mime type, just leave it empty and it will not be used on any platform. Isn't that a more sensible route to go?

**Comment by deltragon** [comment]
Sure, it would be, but that would change existing behaviour (if someone used it on iOS and provided an invalid mime type, that would work now, but break after that change), which i tried to avoid.
I can still modify it to work like that and make a new PR, if that's wanted, since using it with invalid mime types isn't recommended anyways i would guess.

**Comment by pwlin** [comment]
I think providing an invalid mime type and expecting for anything to work smoothly is just short of a miracle :smiley: So I wouldn't worry too much about that. 

I would really appreciate it if you create a new PR for iOS. I just [modified](https://github.com/pwlin/cordova-plugin-file-opener2/commit/7be0278c17a830c83cd73b3270e2a1aca3ed4350) `www/plugins.FileOpener2.js` to set the `contentType` parameter to empty string if it is undefined. So there is no need to perform any check on `[command.arguments count]` in your code, as you will always have `contentType`. You can check if it is an empty string (`""`) then perform an automatic detection, otherwise force the mime type. 

I will do the same for Android by the next weekend.

**Comment by deltragon** [comment]
Will do that.

**Comment by pwlin** [comment]
Thanks for the new PR! Great job! I merged everything to master and will push a new version to `NPM` as soon as I do the same for Android.
