### ISSUE TITLE
Code are different when retrieving from Git and NPM for version 2.0.19

### ISSUE THREAD

**Issue by fhls** [pwlin/cordova-plugin-file-opener2#204]
And the plugin is not working on Android 5 when it is getting from NPM.

**Comment by shnist** [comment]
hi @fhls, thanks for raising this issue. The master branch on github contained a number of fixes after 2.0.19 was published and a new version had not been published for a while. This has been rectified in the new version 2.1.0, which is now available through github and npm. If you upgrade to this version this should resolve the issues you are experiencing on android. If not, please raise another issue with details about what the issue is.

**Comment by fhls** [comment]
@shnist thank you for your reply
