### ISSUE TITLE
contentType is not a consistent cross-platform interface

### ISSUE THREAD

**Issue by keturn** [pwlin/cordova-plugin-file-opener2#22]
the contentType argument to `fileOpener2.open` is a MIME type under Android and a UTI under iOS.

The iOS implementation will try to guess the content type by the file extension[*](https://github.com/pwlin/cordova-plugin-file-opener2/blob/master/src/ios/FileOpener2.m#L43) and the Android docs for Intent say overriding the detected type should "very rarely be used"*, so it is probably best for a cross-platform app to not attempt to specify this value at all.
- http://developer.android.com/reference/android/content/Intent.html#setDataAndType(android.net.Uri, java.lang.String){

(Unless fileOpener2 is able to provide a consistent mapping from MIME types to UTIs.)

**Comment by OmarHallab** [comment]
Hi,

Regarding the MIME type on Android, I am having an issue when selecting the default application to open my files.

Basically if I select ( lets say Excel ) as my default application , it will always open in Excel regardless of the File extension.

Any ideas on how I can resolve this Issue? 

Thanks & appreciate your work

**Comment by pwlin** [comment]
@OmarHallab You opened a new issue about the same exact problem (#115), so let's discuss there.

**Comment by OmarHallab** [comment]
sure, we will proceed there. 

Best Regards,

**Comment by deltragon** [comment]
Actually, under iOS the contentType is argument is being ignored entirely currently, the file extension is used to detect the UTI in all cases.
However, I just submitted a PR addressing this, which (optionally) makes iOS convert the contentType to a UTI using [UTTypeCreatePreferredIdentifierForTag](https://developer.apple.com/documentation/coreservices/1448939-uttypecreatepreferredidentifierf) and use that instead of the file extension since file extensions may be incorrect/missing.

**Comment by shnist** [comment]
hi @keturn, thank you for raising this issue. @deltragon's fixes have now been released in the latest version (2.1.0). If you upgrade to this version your issue should hopefully be resolved.
