### ISSUE TITLE
Open a powerpoint presentation

### ISSUE THREAD

**Issue by mobileComputingNITH** [pwlin/cordova-plugin-file-opener2#38]
Is it possible to open an powerpoint presentation?

For example: 

cordova.plugins.fileOpener2.open(
    '/sdcard/Download/starwars.pptx', 
    'WHAT SHOULD BE HERE',  
    { 
        error : function(e) { 
            console.log('Error status: ' + e.status + ' - Error message: ' + e.message);
        },
        success : function () {
            console.log('file opened successfully');                
        }
    }
);

**Comment by pwlin** [comment]
Yes it's possible to open a powerpoint document, as long as you have any kind of powerpoint viewer app installed on your device.
Try `application/vnd.openxmlformats-officedocument.presentationml.presentation` or `application/vnd.ms-powerpoint` as the second argument instead of `WHAT SHOULD BE HERE`.
