### ISSUE TITLE
Android - Base64 encoded pdf file is not opening

### ISSUE THREAD

**Issue by ravi154** [pwlin/cordova-plugin-file-opener2#66]
I tried opening a base64 encoded string (pdf file) in Android and got the following error -
Error status: 9 - Error message: File not found

Here is the code -
cordova.plugins.fileOpener2.open(base64EncodedPDF, 'application/pdf', {
              error : function(e) {
                  console.log('Error status: ' + e.status + ' - Error message: ' + e.message);
              },
              success : function () {
                  console.log('file opened successfully');
              }
          });
where base64EncodedPDF  = "data:application/pdf;base64,JVBERi0xLjMKJ......."

**Comment by shamaleyte** [comment]
Ravi, when you check the Android Device logs (not app logs) , do you see what I see? 

I have the same error. It saves the file into cdvfile://localhost/persistent/file.pdf
However it is not able to find the file ;
 java.io.IOException: fail to open file. 
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)

Does it somehow relate to this ?  
http://stackoverflow.com/questions/8854359/exception-open-failed-eacces-permission-denied-on-android

**Comment by MadMaxedy** [comment]
@ravi154 Did you already manage to get a solution for this? I'm running into the same issue.

**Comment by ravi154** [comment]
@MadMaxedy I am afraid not. I had to rely on the url to the off file and let the installed off readers open the pdf on the application behalf. Couldn't find a working solution yet.

**Comment by MarkHill89** [comment]
I'm also running into issues trying to get files to open on cordova. Are there any solutions yet anywhere?

**Comment by WuglyakBolgoink** [comment]
up...

**Comment by jonathanwmaddison** [comment]
Just for future issue searchers, you need to download uri to the local filesystem before using the file open plugin: https://github.com/pwlin/cordova-plugin-file-opener2/issues/15
