### ISSUE TITLE
Open a file in iOS - Airdrop appears

### ISSUE THREAD

**Issue by diogodias86** [pwlin/cordova-plugin-file-opener2#73]
Hello,
i'm using the cordova-plugin-file-opener2 plugin to open a file that i download from my server.
In Android its work fine, but in iOS the Airdrop app appears and the file dont open.
The file can be a .pdf, .xls, .doc or a image.

Here is a snippet: 

```
        var url = 'http://myserver.com/file.pdf';
        var nome = url.split("/").pop();
        var options = {};

        var targetPath = cordova.file.externalDataDirectory + nome;

        if (ionic.Platform.isIOS() || ionic.Platform.isIPad()) {
            targetPath = cordova.file.documentsDirectory + nome;
        }

        $cordovaFileTransfer.download(encodeURI(url), targetPath, options, true)
            .then(function (result) {                
                $cordovaFileOpener2.open(
                    result.toURL(),
                    mimetype
                ).then(function () {
                    //sucesso
                }, function (err) {
                    var alert = $ionicPopup.alert({
                            title: 'Erro',
                            template: "Erro ao tentar abrir o arquivo!" + JSON.stringify(err)
                        });
                });
            }, function (err) {
                var alert = $ionicPopup.alert({
                    title: 'Erro',
                    template: "Erro ao tentar fazer o download o arquivo!" + JSON.stringify(err)
                });
            }, function (progress) {
                //$scope.downloadProgress = (progress.loaded / progress.total) * 100;
            });

```

Any idea?? 

Thanks!!

**Comment by Godinall** [comment]
@diogodias86 any luck with it? I'm using the same code and not working too. I'm on a windows env with PhoneGap Desktop. Does this code have to be run in Mac emulator or an actual device?

**Comment by diogodias86** [comment]
hi @Godinall, I decided to fork the project and make my owns editions to meet my needs. 

look at here: https://gist.github.com/diogodias86/bec46de338827c9ef933da19dd0d1e75

i dont know if @pwlin will want my alteration, i think its a specific. If not and @pwlin want, i can merge this with pleasure.

**Comment by Godinall** [comment]
Thanks @diogodias86 , does this have to be run in a Mac environment or simulate on a device? I'm using windows PC for development not sure if this is the problem.

**Comment by diogodias86** [comment]
@Godinall , yes you need run it in iphone/ipad or in a device simulator.

**Comment by elbidone** [comment]
Great Diogo, I've [forked](https://github.com/meumobi/cordova-plugin-file-opener2/tree/feature-display-preview-ios) it and update code as you suggested (add little updates), it works perfectly, no more Airdrop, it opens directly files as done on Android. 
Obrigado!

**Comment by amerlin** [comment]
Hi, I have same problem: when try to open a pdf file (after download and save it from a base 64 stream), i can't open it directly, but by airdrop. I read that there is a fork that resolve it. I'm a newbie, how I can use it? 
Thanks

**Comment by sadikyalcin** [comment]
Any update with this? @diogodias86 your fork does not work for me.

**Comment by elbidone** [comment]
Hi guys, as I commented above I've done a [fork](https://github.com/meumobi/cordova-plugin-file-opener2.git#feature-display-preview-ios) you can use (be careful, it's a branch). I use it in many Apps and works fine, let me know if you face troubles.
The fork should be used exactly as origin plugin, but instead of open airdrop on iOS it opens directly the file. The filename path MUST have an extension (as origin plugin require).

**Comment by pavoltanuska** [comment]
@elbidone your fork works on our side (thanks for that!), but is not up-to-date with this package. Care to fetch from upstream and merge the changes?

Also, why forking it and not sending a PR to this package? (not trying to be offensive, just asking)

**Comment by elbidone** [comment]
Hi @pavoltanuska, @diogodias86 suggested, [on this thread](https://github.com/pwlin/cordova-plugin-file-opener2/issues/73#issuecomment-235702861), to @pwlin to merge its work but never received response, so I deduce he declined such behavior. 
The best way should be to merge it and allow user to choose if he want to use airdrop or not on a plugin config.

**Comment by pwlin** [comment]
@elbidone I have always welcomed all the pull requests. So far I have not receive any PR either from you or @diogodias86. The comment you linked to is a gist. 

Am I right to presume that you would like me to stiff through a gist or an external branch, looking for changes, and then merge everything I have found back into my master branch? 

If that is the case, please tell me so I can do it for you.

Otherwise, I really appreciate it if you send me a decent PR and I'll do my best to merge them.

**Comment by elbidone** [comment]
Hi @pwlin, my link referenced the comment of @diogodias86, not the gist 
> i dont know if @pwlin will want my alteration, i think its a specific. If not and @pwlin want, i can merge this with pleasure.

I prefer to open files without airdrop, but I think it should be a choice to guarantee backward compatibility.
The switch could be done on plugin config (same behavior on whole App) or through js call (select behavior on demand).  I can submit a PR with[ my fork](https://github.com/meumobi/cordova-plugin-file-opener2/tree/feature-display-preview-ios) (replace airdrop w/ direct open) but I can't implement the switch, Objective-C is not my best skill. 

Let me know if you prefer merging from my fork or expect a PR to add the switch strategy of your choice.

**Comment by pwlin** [comment]
@elbidone I am not sure why in that comment @diogodias86 automatically presumes that I won't be interested in his changes and seeks my confirmation first. 

But I think it's better to presume the otherwise. Always send your PR unless the repository owner specifically tells you not to. In that way, it will be the responsibility of the repo owner to decide whether he wants to merge your changes or not. But you have given back what you could for using an open source package. 

As for the specific issue here: I think the notion of "opening in AirDrop" does not belong to this plugin at all, as AirDrop is merely a "share" mechanism and this plugin is a pure "opener". There should be numerous share plugins for Cordova which trigger AirDrop functionality, although they might come with their own bugs and issues. Still, I will try to see if I can make this configurable.

I once again thank you and @diogodias86 for finding a workaround and if you send me a PR from your own fork, I'll see how I can merge it.

**Comment by vicenterusso** [comment]
I had this problem too. Used @diogodias86 solution (just replaced FileOperner2.h and FileOpener2.m) and works fine and fast.

**Comment by pwlin** [comment]
I have received a PR for these changes from @vzharkov and merged everything back to the master branch, bumped the version to `2.0.11` and pushed it to `npm`. Thanks everyone for your help. Please upgrade to the latest version and let me know if there are still issues.
